# docker compose up --build
services:
  mc-server:
    build: .
    container_name: mc-server
    tty: true
    stdin_open: true
    image: ghcr.io/aishukander/mc-server:git
    restart: on-failure
    environment:
      # JAVA_VERSION_OVERRIDE: "<version>"
      # NEO_VERSION_OVERRIDE: "<version>"
      Type: "paper"
      MINECRAFT_VERSION: "26.2"
      Min_Ram: "1G"
      Max_Ram: "4G"
      #JAVA_OPTS: ""
      user: "1000:1000"
    volumes:
      - ./server:/project/server
      - ./java:/project/java
    ports:
      - "25565:25565"