# docker compose up --build
services:
  mc-server:
    build: .
    container_name: mc-server
    tty: true
    stdin_open: true
    image: aishukander/mc-server
    restart: on-failure
    environment:
      # JAVA_VERSION_OVERRIDE: "<version>"
      # NEO_VERSION_OVERRIDE: "<version>"
      Type: "paper"
      MINECRAFT_VERSION: "1.21.1"
      Min_Ram: "1G"
      Max_Ram: "4G"
    volumes:
      - ./server:/project/server
      - ./java:/project/java
    ports:
      - "25565:25565"