name: Cleanup Untagged Images

on:
  workflow_run:
    workflows: ["Docker Publish"] 
    types:
      - completed

jobs:
  delete-untagged-images:
    if: github.event.workflow_run.conclusion == 'success'
    
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read 
    
    steps:
      - name: Delete untagged versions
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }} 
          package-name: ${{ github.event.repository.name }} 
          package-type: 'container'


          delete-only-untagged-versions: true 
          min-versions-to-keep: 0